name = "cloudflare-ai-app"
main = "src/worker.ts"
compatibility_date = "2024-10-01"

[ai]
binding = "AI"

[durable_objects]
bindings = [
  { name = "CHAT_SESSIONS", class_name = "ChatSession" }
]

[[migrations]]
tag = "v1-add-chat-session"
new_classes = ["ChatSession"]

[assets]
directory = "public"


